# Generated by Django 2.2.7 on 2019-11-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_weight', models.IntegerField(max_length=10)),
                ('current_weight', models.IntegerField(max_length=10)),
                ('end_weight', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Routine', max_length=100)),
                ('week', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=50)),
                ('sets', models.IntegerField(max_length=50)),
                ('reps', models.IntegerField(max_length=50)),
            ],
        ),
    ]
