# Generated by Django 2.2.7 on 2019-11-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forfit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='end_weight',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_weight',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='sets',
        ),
    ]
